# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_end_esp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 350, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 380, 311, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 380, 75, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(420, 190, 141, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(310, 190, 111, 21))
        self.label_15.setObjectName("label_15")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 721, 171))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 20, 151, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 50, 41, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 20, 41, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(100, 80, 41, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(100, 110, 41, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 51, 16))
        self.label_19.setObjectName("label_19")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 16, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 30, 41, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 41, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 50, 21, 16))
        self.label.setObjectName("label")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(100, 110, 41, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 141, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_15.setGeometry(QtCore.QRect(310, 60, 41, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(200, 50, 111, 41))
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(160, 80, 151, 41))
        self.label_14.setObjectName("label_14")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_16.setGeometry(QtCore.QRect(310, 90, 41, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_18.setGeometry(QtCore.QRect(310, 120, 41, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(190, 120, 121, 20))
        self.label_17.setObjectName("label_17")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 50, 181, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(30, 20, 91, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 50, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 20, 41, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 121, 20))
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 250, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(150, 310, 251, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 310, 121, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(390, 250, 161, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 180, 141, 31))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setGeometry(QtCore.QRect(180, 230, 41, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 220, 121, 31))
        self.label_18.setObjectName("label_18")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(420, 220, 141, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 350, 331, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(270, 220, 151, 21))
        self.label_22.setObjectName("label_22")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 410, 261, 20))
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 410, 75, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(40, 190, 131, 41))
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 260, 151, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setGeometry(QtCore.QRect(180, 260, 41, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Propagador de campo óptico"))
        self.pushButton.setText(_translate("MainWindow", "Guardar"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Guardar intensidad en los planos XZ y XY:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Guardar"))
        self.comboBox.setItemText(0, _translate("MainWindow", "VPP (helicoidal 0-2pi)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Nula (haz gaussiano)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Elegida por el usuario"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Máscara de fase:</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Parámetros"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Resolución (nm)"))
        self.lineEdit_4.setText(_translate("MainWindow", "8"))
        self.label_6.setText(_translate("MainWindow", "Resolución axial  "))
        self.lineEdit_5.setText(_translate("MainWindow", "5"))
        self.label_4.setText(_translate("MainWindow", "Resolución radial  "))
        self.label_16.setText(_translate("MainWindow", " FOV radial"))
        self.lineEdit_17.setText(_translate("MainWindow", "1000"))
        self.lineEdit_20.setText(_translate("MainWindow", "2000"))
        self.label_19.setText(_translate("MainWindow", " FOV axial"))
        self.label_2.setText(_translate("MainWindow", "n"))
        self.lineEdit_3.setText(_translate("MainWindow", "640"))
        self.lineEdit.setText(_translate("MainWindow", "1.4"))
        self.lineEdit_2.setText(_translate("MainWindow", "1.5"))
        self.label.setText(_translate("MainWindow", "NA"))
        self.lineEdit_12.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Long. de onda en vacío (nm)"))
        self.lineEdit_15.setText(_translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "Intensidad (kW/cm^2)"))
        self.label_14.setText(_translate("MainWindow", "Radio del haz gaussiano (mm)"))
        self.lineEdit_16.setText(_translate("MainWindow", "5"))
        self.lineEdit_18.setText(_translate("MainWindow", "3"))
        self.label_17.setText(_translate("MainWindow", "Radio de apertura (mm)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Polarización"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'arial,sans-serif\'; color:#222222; background-color:#ffffff;\">Δ </span>fase (grados)</p></body></html>"))
        self.lineEdit_11.setText(_translate("MainWindow", "45"))
        self.lineEdit_13.setText(_translate("MainWindow", "90"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>tan<span style=\" font-family:\'arial,sans-serif\'; color:#3c4043; background-color:#ffffff;\">−1</span>(Ey/Ex) (grados)</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Posición en Z del"))
        self.label_11.setText(_translate("MainWindow", "plano XY (z0) (nm)"))
        self.pushButton_3.setText(_translate("MainWindow", "Simular"))
        self.lineEdit_14.setText(_translate("MainWindow", "(dejar así para usar carpeta local)"))
        self.pushButton_5.setText(_translate("MainWindow", "Carpeta de guardado"))
        self.pushButton_6.setText(_translate("MainWindow", "Borrar pestañas de imágenes "))
        self.radioButton.setText(_translate("MainWindow", "Simular difracción entre"))
        self.lineEdit_19.setText(_translate("MainWindow", "1000"))
        self.label_3.setText(_translate("MainWindow", " de fase y lente (mm)"))
        self.label_18.setText(_translate("MainWindow", "Distancia entre máscara"))
        self.lineEdit_21.setText(_translate("MainWindow", "Simulación máscara VPP"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Guardar un texto con los parámetros usados:</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Nombre de la simulación:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Guardar amplitudes en el plano XY:</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Guardar"))
        self.label_20.setText(_translate("MainWindow", "máscara de fase y objetivo"))
        self.label_23.setText(_translate("MainWindow", "Radio de máscara de fase (mm)"))
        self.lineEdit_22.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

